# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=16)),
                ('picture_url', models.CharField(max_length=200)),
                ('posting_date', models.DateTimeField()),
            ],
        ),
    ]
